// Offline KQL semantic check using Microsoft's Kusto.Language (npm @kusto/language-service-next).
// Usage: NODE_PATH=<dir containing node_modules> [PRELUDE=prelude.kql] node kqlcheck.js schemas.json file1.kql [...]
// PRELUDE (optional): KQL let-statements prepended to every file (stubs for _GetWatchlist and the pack's saved
// functions, generated by make_prelude.py). Diagnostics inside the prelude itself are reported against the prelude.
// Builds table symbols from the column lists scraped from Microsoft Learn (schemas.json), then parses and binds
// each query. Reports syntax errors, unknown tables/columns, type errors. It does NOT check data or runtime limits.
require('@kusto/language-service-next/bridge.min.js');
require('@kusto/language-service-next/Kusto.Language.Bridge.min.js');
const fs = require('fs');
const K = Kusto.Language;
const typeMap = { boolean: 'bool', bool: 'bool', integer: 'int', int: 'int', long: 'long', real: 'real',
  double: 'real', string: 'string', datetime: 'datetime', dynamic: 'dynamic', guid: 'guid', timespan: 'timespan',
  decimal: 'decimal' };
const schemas = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const tables = [];
for (const [name, info] of Object.entries(schemas)) {
  const cols = [];
  const seen = new Set();
  for (const c of info.cols) {
    const [col, typ] = c;
    if (!col || ['Categories', 'Solutions'].includes(col) || seen.has(col)) continue;
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(col)) continue;
    seen.add(col);
    cols.push(`['${col}']:${typeMap[(typ || 'string').toLowerCase()] || 'string'}`);
  }
  tables.push(new K.Symbols.TableSymbol.$ctor7(name, '(' + cols.join(', ') + ')', ''));
}
const db = new K.Symbols.DatabaseSymbol.$ctor3('workspace', null, Bridge.toList(tables), false);
const globals = K.GlobalState.Default.WithDatabase(db);
const prelude = process.env.PRELUDE ? fs.readFileSync(process.env.PRELUDE, 'utf8') : '';
const preludeLines = prelude ? prelude.split('\n').length - 1 : 0;
let failed = 0;
for (const f of process.argv.slice(3)) {
  const own = fs.readFileSync(f, 'utf8');
  // A file that is itself a function body (functions/*.kql) is checked standalone with the prelude.
  const text = prelude + own;
  const code = K.KustoCode.ParseAndAnalyze(text, globals);
  const d = code.GetDiagnostics();
  const issues = [];
  for (let i = 0; i < d.Count; i++) {
    const x = d.getItem(i);
    const abs = text.slice(0, x.Start).split('\n').length;
    const where = abs > preludeLines ? `line ${abs - preludeLines}` : `prelude line ${abs}`;
    issues.push(`  ${x.Severity} ${where}: ${x.Message}`);
  }
  const errors = issues.filter(s => s.includes('Error'));
  if (errors.length) failed++;
  console.log(`${errors.length ? 'FAIL' : 'PASS'}  ${f.split('/').pop()}  (${issues.length} diagnostics)`);
  issues.forEach(s => console.log(s));
}
console.log(`\n${process.argv.length - 3 - failed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
